;*******************************************************************************
; TITLE : EXERCISE 3.2
; PROFESSOR: MARTIN DEL BARCO			
; AUTHOR: VALENZUELA GABRIEL EMANUEL
; SUBJET: DIGITAL ELECTRONICS II
; INSTITUTE : FEFYN - UNC
; DATE: 04-08-2019
; VERSION: 1.0.2
; CHANGE VERSION 1.0.0 TO 1.0.2: SOLVE BUG WITH THE OUPUTS.
;
; RESUME:
; THIS PROGRAM SWICHT TWO LEDS ON RB2/RB3 ACCORDING TO RA4 AND RB0
;*******************************************************************************			
#include "p16f887.inc"	;HEADER THAT CONTAINS ALL ADDRESS MEMORY DEFINED BY MI-
			;CROCHIP
    LIST P=16F887	;DEFINE THE MICROCONTROLLER TO BE USED.			
;*******************************************************************************
    ; __config 0x3FF1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    ORG 0x00
    GOTO PROGRAM
    
    
PROGRAM: ORG 0x05
	
	CLRW		;CLEAR THE WORK REGISTER
	CALL CONFIGURE_PORTS
	CLRW
	CLRF PORTA
	CLRF PORTB
LOOP:	MOVFW PORTA	    ;MOVE THE CONTENT OF PORTA TO W
	BTFSC PORTA,RA4	    ;IF RA4 == 0 ?
	GOTO ILRB2	    ;FALSE --> LED RB3 ON
	GOTO OLRB2	    ;TRUE -->  LED RB3 OFF
LOOPS:	BTFSC PORTB,RB0	    ;IF RB0 == 0 ?
	GOTO ILRB3	    ;FALSE --> LED RB4 ON
	GOTO OLRB3	    ;TRUE -->  LED RB4 OFF
OLRB2:  BCF PORTB,RB2
	GOTO LOOPS
ILRB2:	BSF PORTB,RB2
	GOTO LOOPS
OLRB3:  BCF PORTB,RB3
	GOTO LOOP
ILRB3:	BSF PORTB,RB3
	GOTO LOOP
	;INFINITY LOOP
;*******************************************************************************
;				SUBRUTINE
CONFIGURE_PORTS: ORG 0X1A
    ;GO TO BANK 1, THAT IS, RP1 = 0 AND RP0=1
    BCF STATUS,RP1
    BSF STATUS,RP0
    CLRF TRISA
    CLRF TRISB
    MOVLW B'00010000'	;RA<4> IS A INPUT
    MOVWF TRISA
    MOVLW B'00000001'	;RB<0> IS A INPUT
    MOVWF TRISB
    ;GO TO ANSELH TO SET RB0 LIKE DIGITAL INPUT
    BSF STATUS,RP1
    CLRF ANSELH
    CLRF ANSEL
    BCF STATUS,RP0
    BCF STATUS,RP1
    RETURN
    
    END