;*******************************************************************************
; TITLE : EXERCISE 3.7
; PROFESSOR: MARTIN DEL BARCO			
; AUTHOR: VALENZUELA GABRIEL EMANUEL
; SUBJET: DIGITAL ELECTRONICS II
; INSTITUTE : FEFYN - UNC
; DATE: 04-08-2019
; VERSION: 1.0.0
;
; RESUME:
; THIS PROGRAM COUNT FROM 0 TO E USING A SEVEN SEGMENT DISPLAY
;*******************************************************************************			
#include "p16f887.inc"	;HEADER THAT CONTAINS ALL ADDRESS MEMORY DEFINED BY MI-
			;CROCHIP
#INCLUDE "__tables.inc"
#INCLUDE "__subrutines.inc"
			
    LIST P=16F887	;DEFINE THE MICROCONTROLLER TO BE USED.			
;*******************************************************************************
    ; __config 0x3FF1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    ORG 0x00
    GOTO PROGRAM
    ORG 0x04
    BCF STATUS,RP0
    BCF STATUS,RP1
    BTFSS PORTB,RB0
    GOTO TMR_INT
    GOTO BTN_INT
    
DELAY_50MS EQU 0XC3
MULTIPLIER_FACTOR EQU 0X14
COUNTER EQU 0X20
TIME_REG EQU 0x21
SIZE_ARRAY SET  0xA
PROGRAM: ORG 0x20

START
    CLRW
    CLRF COUNTER
    BANKSEL TRISB
    MOVLW B'00000001'
    MOVWF TRISB
    MOVLW 0xFF
    MOVWF TRISD
    BANKSEL INTCON
    BCF INTCON,INTE
    BANKSEL PORTB
    MOVLW 0x00
    MOVWF PORTB
IN  BTFSS PORTB,RB0
    GOTO IN
    CLRF PORTD
    CALL CONFIGURE_TRIS

    CALL INIT_TIMER
    MOVLW 0xA
    MOVWF COUNTER
    GOTO PROGRAM_MAIN
PROGRAM_MAIN
    GOTO $
	;000-0-1010 --- MAX NUMBER
;*******************************************************************************
;				SUBRUTINE


TMR_INT: ORG 0x100
    MOVLW   DELAY_50MS
    MOVWF   TMR0
    DECFSZ  TIME_REG,F
    GOTO    END_INT
    DECF    COUNTER,F		;DECREMENT COUNT
    BTFSS   STATUS,Z		;THE Z FLAG IS AFFECTED ?
    GOTO    INCR		;FALSE--> INCREMENT THE COUNT
    GOTO    RESET_COUNT		;TRUE --> RESET THE COUNT
INCR
    MOVFW   COUNTER
    SUBLW   SIZE_ARRAY		;COUNTER (10) - X --> W
    CALL    NUMBERS		;CALL TABLE WITH THE RESULT. E.G 10 - 10 = 0
    MOVWF   PORTD		;LATCH PORTD
    MOVLW   MULTIPLIER_FACTOR	;RESET TIMER
    GOTO    TIME		;MOV TO MULTIPLER FACTOR
RESET_COUNT
    MOVF COUNTER,W
    CALL NUMBERS
    MOVWF PORTD
    MOVLW 0xA
    MOVWF COUNTER
    MOVLW MULTIPLIER_FACTOR
TIME
    MOVWF   TIME_REG
END_INT
    BCF	    INTCON,T0IF
    RETFIE		;GIE
BTN_INT: ORG 0x0E
    MOVFW COUNTER
    SUBLW SIZE_ARRAY
    BTFSS STATUS,Z 
    GOTO RESET_COUNT
    MOVLW 0x0
    CALL NUMBERS
    MOVWF PORTD
    RETFIE
    END